import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import {
  HiOutlineSparkles,
  HiOutlineDocumentMagnifyingGlass,
  HiOutlineMicrophone,
  HiOutlineClipboardDocumentList,
  HiOutlineUserPlus,
  HiOutlineCpuChip,
  HiOutlineStar,
  HiOutlineCheckCircle,
  HiOutlineBolt,
  HiOutlineChatBubbleLeftRight,
  HiOutlineBriefcase,
} from 'react-icons/hi2'
import PublicLayout from '../layouts/PublicLayout'
import Button from '../components/Button'

const features = [
  {
    icon: HiOutlineSparkles,
    title: 'Opportunity Finder Agent',
    desc: 'An AI agent that scans thousands of listings daily from Internshala, Naukri, and Foundit matched to your skills.',
  },
  {
    icon: HiOutlineDocumentMagnifyingGlass,
    title: 'Resume ATS Analyzer',
    desc: 'Get instant feedback, skill gap analysis, and ATS resume scoring to land more interviews.',
  },
  {
    icon: HiOutlineCpuChip,
    title: 'Gemini AI Match Scoring',
    desc: 'Smart recommendations ranked by real candidate match percentage (98% fit score), not just keywords.',
  },
  {
    icon: HiOutlineMicrophone,
    title: 'AI Interview Preparation',
    desc: 'Practice with role-specific technical questions and model answers generated by Gemini AI.',
  },
  {
    icon: HiOutlineClipboardDocumentList,
    title: 'Live Application Tracker',
    desc: 'Track every application from applied to offer in one organized database-connected dashboard.',
  },
]

const steps = [
  { step: '01', title: 'Create your profile', desc: 'Tell us your skills, degree, experience and target location.' },
  { step: '02', title: 'Let AI agents work', desc: 'Gemini AI matches you to live jobs, internships and hackathons.' },
  { step: '03', title: '1-Click Direct Apply', desc: 'Apply in one click or receive instant WhatsApp & Gmail alerts.' },
  { step: '04', title: 'Land the offer', desc: 'Prep smarter with AI interview coaching and land top software roles.' },
]

const testimonials = [
  { name: 'Ananya Rao', role: 'Frontend Developer @ TechCorp', quote: 'Agentic AI matched me to roles in Chennai I would never have found on my own. 1-Click apply is amazing.' },
  { name: 'Rahul Mehta', role: 'AI Engineer @ InnovateAI', quote: 'The interview prep module felt like having a personal coach. I walked into interviews genuinely prepared.' },
  { name: 'Sneha Iyer', role: 'Product Designer @ DesignHub', quote: 'Tracking every application and getting WhatsApp AI notifications saved me hours every week.' },
]

export default function LandingPage() {
  const navigate = useNavigate()
  return (
    <PublicLayout>
      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-6 pt-12 pb-20 grid lg:grid-cols-2 gap-12 items-center">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
          <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-forest-50 border border-forest-200 text-forest-700 text-xs font-medium mb-6">
            <HiOutlineSparkles className="text-sm text-forest-600" />
            AI-Powered Career &amp; Opportunity Finder
          </div>

          <h1 className="text-5xl sm:text-6xl font-extrabold leading-[1.05] text-ink">
            Find Jobs, Internships and Hackathons using <span className="text-forest-600">AI Agents</span>
          </h1>
          <p className="text-ink-light text-lg mt-6 max-w-lg leading-relaxed">
            Discover opportunities that match your skills and ambitions — powered by AI that works around the clock, so you don't have to search alone.
          </p>
          <div className="flex flex-wrap gap-4 mt-8">
            <Button onClick={() => navigate('/register')}>Get Started</Button>
            <Button variant="secondary" onClick={() => navigate('/jobs')}>Explore Opportunities</Button>
          </div>

          <div className="grid grid-cols-2 gap-4 mt-12">
            {[
              { icon: HiOutlineCpuChip, title: 'AI Matching', desc: 'Smart recommendations just for you' },
              { icon: HiOutlineDocumentMagnifyingGlass, title: 'Resume Analyzer', desc: 'Improve your resume with AI insights' },
              { icon: HiOutlineMicrophone, title: 'Interview Prep', desc: 'Practice and ace your interviews' },
              { icon: HiOutlineClipboardDocumentList, title: 'Application Tracker', desc: 'Track and manage all your applications' },
            ].map((f) => (
              <div key={f.title} className="card p-4">
                <f.icon className="text-forest-600 text-xl mb-2" />
                <p className="font-semibold text-sm text-ink">{f.title}</p>
                <p className="text-xs text-ink-muted mt-1">{f.desc}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Hero Right Panel: Clean, Pure Text & Key Platform Features Overview */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.7 }}
          className="relative"
        >
          <div className="card p-8 bg-white border border-border/80 shadow-card rounded-3xl space-y-6">
            <div className="border-b border-border pb-4">
              <span className="badge bg-forest-50 text-forest-700 font-semibold text-xs border border-forest-200 mb-2">
                Platform Capabilities
              </span>
              <h3 className="font-extrabold text-2xl text-ink">How Agentic AI Powers Your Search</h3>
              <p className="text-sm text-ink-muted mt-1 leading-relaxed">
                Autonomous AI agents working 24/7 to connect candidates directly with live opportunities.
              </p>
            </div>

            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <span className="w-8 h-8 rounded-lg bg-forest-50 text-forest-600 flex items-center justify-center shrink-0 mt-0.5">
                  <HiOutlineBolt className="text-lg" />
                </span>
                <div>
                  <h4 className="font-bold text-sm text-ink">Autonomous Multi-Platform Scanner</h4>
                  <p className="text-xs text-ink-light mt-0.5 leading-relaxed">
                    Continuously aggregates real-time openings from <strong>Internshala, Naukri, and Foundit</strong> across Chennai, Coimbatore, Bangalore &amp; Remote India.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <span className="w-8 h-8 rounded-lg bg-forest-50 text-forest-600 flex items-center justify-center shrink-0 mt-0.5">
                  <HiOutlineBriefcase className="text-lg" />
                </span>
                <div>
                  <h4 className="font-bold text-sm text-ink">1-Click In-App Direct Application</h4>
                  <p className="text-xs text-ink-light mt-0.5 leading-relaxed">
                    Apply instantly within the platform without generic website redirection loops or broken pages.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <span className="w-8 h-8 rounded-lg bg-forest-50 text-forest-600 flex items-center justify-center shrink-0 mt-0.5">
                  <HiOutlineDocumentMagnifyingGlass className="text-lg" />
                </span>
                <div>
                  <h4 className="font-bold text-sm text-ink">Gemini AI ATS Resume Analyzer</h4>
                  <p className="text-xs text-ink-light mt-0.5 leading-relaxed">
                    Auto-fills candidate profile &amp; education details, calculates 88% ATS fit scores, and provides skill gap recommendations.
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <span className="w-8 h-8 rounded-lg bg-forest-50 text-forest-600 flex items-center justify-center shrink-0 mt-0.5">
                  <HiOutlineChatBubbleLeftRight className="text-lg" />
                </span>
                <div>
                  <h4 className="font-bold text-sm text-ink">WhatsApp &amp; Gmail AI Job Alerts</h4>
                  <p className="text-xs text-ink-light mt-0.5 leading-relaxed">
                    Personalized AI-generated WhatsApp messages and Gmail email notifications sent directly to your phone.
                  </p>
                </div>
              </div>
            </div>

            <div className="pt-4 border-t border-border flex items-center justify-between text-xs">
              <span className="text-emerald-700 font-semibold flex items-center gap-1">
                <HiOutlineCheckCircle /> Real-Time Database Sync Active
              </span>
              <button onClick={() => navigate('/register')} className="text-forest-600 font-bold hover:underline">
                Create Free Profile →
              </button>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section id="features" className="bg-white border-y border-border py-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-xl mx-auto mb-14">
            <h2 className="text-3xl font-bold text-ink">Everything you need, in one platform</h2>
            <p className="text-ink-muted mt-3">AI agents that work behind the scenes so your job search runs itself.</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f) => (
              <div key={f.title} className="card p-6 hover:shadow-soft transition-shadow">
                <span className="w-12 h-12 rounded-xl bg-forest-50 text-forest-600 flex items-center justify-center mb-4">
                  <f.icon className="text-2xl" />
                </span>
                <h3 className="font-semibold text-ink">{f.title}</h3>
                <p className="text-sm text-ink-muted mt-2">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="about" className="py-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-xl mx-auto mb-14">
            <h2 className="text-3xl font-bold text-ink">How it works</h2>
            <p className="text-ink-muted mt-3">Four simple steps from profile to offer letter.</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map((s) => (
              <div key={s.step} className="relative">
                <span className="text-4xl font-extrabold text-forest-100">{s.step}</span>
                <h3 className="font-semibold text-ink mt-2">{s.title}</h3>
                <p className="text-sm text-ink-muted mt-2">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="bg-forest-800 py-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-xl mx-auto mb-14">
            <h2 className="text-3xl font-bold text-white">Loved by job seekers</h2>
            <p className="text-forest-200 mt-3">Real outcomes from candidates who used Agentic AI to land top software roles.</p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {testimonials.map((t) => (
              <div key={t.name} className="bg-forest-700/60 border border-forest-600 rounded-2xl p-6">
                <div className="flex gap-1 text-amber-400 mb-3">
                  {Array.from({ length: 5 }).map((_, i) => <HiOutlineStar key={i} />)}
                </div>
                <p className="text-forest-100 text-sm leading-relaxed">"{t.quote}"</p>
                <p className="text-white font-semibold text-sm mt-4">{t.name}</p>
                <p className="text-forest-300 text-xs">{t.role}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 text-center px-6">
        <HiOutlineUserPlus className="text-forest-600 text-4xl mx-auto mb-4" />
        <h2 className="text-3xl font-bold text-ink">Ready to empower your future?</h2>
        <p className="text-ink-muted mt-3">Create your free profile and let AI agents find your next opportunity.</p>
        <Button className="mt-7" onClick={() => navigate('/register')}>Get Started for Free</Button>
      </section>
    </PublicLayout>
  )
}
